version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - anastasiia-bilova
  ignore:
  - dependency-name: pylint
    versions:
    - 2.7.0
    - 2.7.3
  - dependency-name: ddt
    versions:
    - 1.4.2
